version: "3.9"
services:
  no-batch:
    build: .
    links:
      - locust
  batch-1:
    build: .
    links:
      - locust
  batch-32:
    build: .
    links:
      - locust
  batch-64:
    build: .
    links:
      - locust
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py
